### ISSUE TITLE
关于BufferPool类中的一个问题

### ISSUE THREAD

**Issue by 978326187** [iamxpy/SimpleDB#3]
请问BufferPool类在实现的时候为什么要用一个HashMap<PageId, Page>呢，是因为cache里面的PageID和Page类中的pageID代表的不是一个东西吗？

**Comment by adiamoe** [comment]
如果是指LruCache中的cachedEntries的话，用HashMap是为了便于查找。因为在真实的数据库中，Page的数量级是很大的，如果不用HashMap，用遍历的方式去寻找对应页，效率很低，这是一种优化的方式，同时方便实现LRU替换。PageID都是Page对应的标识，毕竟在同一个Package下。

当然因为这是一个简易数据库，按照课程项目的原意不需要设计这样的LruCache，也可以考虑在BufferPool中直接开辟Page的数组/List，用遍历的方式寻找对应页，用Clock Alogrithm或者其他方式实现页面的替换。
